### ISSUE TITLE
Configure SQL Server database

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/sbeap#12]
Add a "Sbeap" database and app user in Dev, UAT, & Prod environments.
```[tasklist]
### Tasks
- [x] Dev
- [x] UAT
- [x] Prod
```

**Comment by afatima16** [comment]
@dougwaldron, I have completed the request on DEV Db Server (.83) . Can you please review it and let me know so I can work accordingly on UAT and DEV. 
here is the information for app user https://github.com/gaepdit/app-config/edit/main/sql-server-accounts.md

**Comment by dougwaldron** [comment]
Dev tested and validated. Please proceed with UAT & Prod when convenient. Thanks!

**Comment by afatima16** [comment]
@dougwaldron, Request is completed on both UAT DB (.82) and prod Db Server (.242). Please review it when convenient. Thanks!
here is the information for app user password: https://github.com/gaepdit/app-config/edit/main/sql-server-accounts.md

**Comment by dougwaldron** [comment]
@afatima16 I'd like to try a different strategy for app deployment. Can you please create a second user called "sbeap_migration" with DDL access? The new user will be used only for app deployment, while the existing app user will be used for routine data access.

If you could make this change on the UAT server first, it would be easier to test the setup there. Thanks!

**Comment by dougwaldron** [comment]
@afatima16: I deployed to prod this afternoon. Works great. Thanks for your help on this!!
