### ISSUE TITLE
Reevaluate nav bar and footer

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/sbeap#161]
Some options to consider:

- [x] Combine [logo into navbar](https://getbootstrap.com/docs/5.3/examples/headers/).
- [x] Make navbar sticky to top (may conflict with "Test Site" banner).
- [x] Use the new [nav-underline](https://getbootstrap.com/docs/5.3/components/navs-tabs/#underline) style.
- [x] ~Use an [offcanvas navbar](https://getbootstrap.com/docs/5.3/examples/navbars-offcanvas/).~ *Offcanvas navbar is nice, but current one works fine.*
- [x] Use a different [sticky footer](https://getbootstrap.com/docs/5.3/examples/sticky-footer-navbar/) technique.
- [x] Make the footer colors more subtle.
- [x] Use `<button>` in menu instead of `<a role=button>`.

**Comment by DilushaHesaranga** [comment]
### Hey there!!!
I am **very interested** on this work 
Can you **assign me to** work on :-)

**Comment by dougwaldron** [comment]
@DilushaHesaranga Thanks for your interest! But as you can see I've already submitted a PR that completes and closes the issue: #163

Would you be interested in helping with this one? https://github.com/dougwaldron/podcast-rewind/issues/45

**Comment by DilushaHesaranga** [comment]
@dougwaldron Got it.
I'll be working on #45
