### ISSUE TITLE
Refresh UAT/DEV databases

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/sbeap#178]
When you get a chance, please copy the Prod SBEAP database to UAT & Dev. Thanks.

**Comment by afatima16** [comment]
@dougwaldron. SBEAP database is successfully copied from PROD to DEV (.83). Please verify at your convenience. I'm working on UAT server and will keep you updated. Thanks

**Comment by dougwaldron** [comment]
@afatima16 Dev looks good!

**Comment by afatima16** [comment]
@afatima16 SBEAP database is successfully copied from PROD to UAT (.82). Please verify at your convenience. Thanks!

**Comment by dougwaldron** [comment]
@afatima16 UAT looks good too, thanks for your help!
