### ISSUE TITLE
Document workflow/UI

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/sbeap#24]
Document the business use cases and workflow and define the UI pages needed. Create a [site map](https://github.com/gaepdit/sbeap/blob/fea1a74162fee4ed758220fe3aafeeb9428aeafa/docs/Site%20map.md).

Use the [Current SBEAP app workflow](https://github.com/gaepdit/sbeap/discussions/13) for reference.

**Comment by MDLopezRios** [comment]
See Discussions tap for reference(s) material
